workflows:
  my-workflow:
    environment:
      flutter: 2.2.3
      java: 11
    scripts:
      - name: Set up local.properties
        script: |
                    echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
                    cd . && flutter packages pub get
      - name: Flutter analyze
        script: |
                    cd . && flutter analyze
      - name: Flutter unit tests
        script: |
                    cd . && flutter test
        ignore_failure: true
      - name: Build APK with Flutter
        script: |
                  - flutter build apk --debug --flavor develop
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - ipan.rahman@gmail.com
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: develop
          include: true
      cancel_previous_builds: true
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches